# tests boxplots
par(mfrow=c(1,5))
report001 <- read.delim("report001", header = TRUE, sep = " ")
boxplot(tests ~ category, data = report001, col = "lightgray")
report002 <- read.delim("report002", header = TRUE, sep = " ")
boxplot(tests ~ category, data = report002, col = "lightgray")
report004 <- read.delim("report004", header = TRUE, sep = " ")
boxplot(tests ~ category, data = report004, col = "lightgray")
report008 <- read.delim("report008", header = TRUE, sep = " ")
boxplot(tests ~ category, data = report008, col = "lightgray")
report012 <- read.delim("report012", header = TRUE, sep = " ")
boxplot(tests ~ category, data = report012, col = "lightgray")


# exp growth
#par(mfrow=c(1,4))
#growth25 <- read.delim("report25", header = TRUE, sep = " ")
#model <- drm(tests ~ distance, fct = EXD.2(), data = growth25)
#plot(model, log="", type="all")
#growth50 <- read.delim("report50", header = TRUE, sep = " ")
#model <- drm(tests ~ distance, fct = EXD.2(), data = growth50)
#plot(model, log="", type="all")
#growth75 <- read.delim("report75", header = TRUE, sep = " ")
#model <- drm(tests ~ distance, fct = EXD.2(), data = growth75)
#plot(model, log="", type="all")
#growth100 <- read.delim("report100", header = TRUE, sep = " ")
#model <- drm(tests ~ distance, fct = EXD.2(), data = growth100)
#plot(model, log="", type="all")
